# frozen_string_literal: true

artifact = File.realpath(ARGV.fetch(0))
source_lib = File.realpath(ARGV.fetch(1))
profile_root = File.dirname(File.dirname(artifact))
source_info = File.realpath(File.join(source_lib, "racc/info.rb"))
source_parser = File.realpath(File.join(source_lib, "racc/parser.rb"))

# Keep installed Racc Ruby and native files unreachable. The pinned source
# parser can resolve only its info file and the exact staged cparse artifact.
$LOAD_PATH.replace([profile_root, source_lib])
require source_parser

loaded = $LOADED_FEATURES.map { |path| File.realpath(path) rescue path }
abort "exact Racc artifact was not loaded" unless loaded.include?(artifact)
abort "source Racc parser runtime was not loaded" unless loaded.include?(source_parser)
abort "source Racc info was not loaded" unless loaded.include?(source_info)

native_features = loaded.grep(%r{/racc/cparse\.(?:so|bundle|dll)\z})
unless native_features == [artifact]
  abort "unexpected Racc native runtime loaded: #{native_features.inspect}"
end

native_methods = Racc::Parser.private_instance_methods
unless native_methods.include?(:_racc_do_parse_c) &&
       native_methods.include?(:_racc_yyparse_c)
  abort "Racc native parser methods are missing"
end

unless Racc::Parser::Racc_Runtime_Core_Version_C == Racc::VERSION
  abort "Racc native runtime version differs from source lib/racc/info.rb"
end
abort "Racc selected the Ruby fallback runtime" unless
  Racc::Parser.racc_runtime_type == "c"
unless Racc::Parser.instance_method(:_racc_do_parse_c).source_location.nil?
  abort "Racc native parse entrypoint is not implemented by the staged DSO"
end

# Generated by pinned Racc 1.8.1 from the grammar:
#   target : NUMBER { result = val[0] }
# Keeping the transition table here proves the native runtime without relying
# on parser-text.rb, a release artifact generated by rake srcs and intentionally
# absent from the pinned Git source tree.
class NativeSmokeParser < Racc::Parser
  Racc_arg = [
    [2, 3, 4],
    [0, 1, 3],
    [-2, -2, -1, -2, 5],
    [-2, 1, nil, 2, nil],
    [1],
    [1],
    [nil, nil],
    [nil, 0],
    3,
    [0, 0, :racc_error, 1, 4, :_reduce_1],
    { false => 0, error: 1, NUMBER: 2 },
    5,
    2,
    true
  ]
  Racc_token_to_s_table = ["$end", "error", "NUMBER", "$start", "target"]
  Racc_debug_parser = false

  Ractor.make_shareable(Racc_arg) if defined?(Ractor)
  Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

  def parse(value)
    @tokens = [[:NUMBER, value], [false, false]]
    do_parse
  end

  def next_token
    @tokens.shift
  end

  def _reduce_1(values, _value_stack, _result)
    values[0]
  end

  def _reduce_none(values, _value_stack, _result)
    values[0]
  end
end

parser = NativeSmokeParser.new
{ 42 => 42, "zig-racc" => "zig-racc" }.each do |input, expected|
  actual = parser.parse(input)
  abort "native Racc parse failed: #{actual.inspect}" unless actual == expected
end

puts "Racc exact artifact native parser runtime passed"
